<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-ContractSeedGrower</name>
   <tag></tag>
   <elementGuidId>f523c7a6-0e85-47b8-84c7-b1b1e0c2470b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[3]/div/div[1]/div[1]/div[1]/div/button[2]</value>
   </webElementProperties>
</WebElementEntity>
