<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input-SearchProfile</name>
   <tag></tag>
   <elementGuidId>e5e17c9e-83ae-483b-ad5b-cf2840a0eb05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[3]/div/div/div/span[2]/div[1]/div[2]/div/input</value>
   </webElementProperties>
</WebElementEntity>
