<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link-edit-AddPhoneNumber</name>
   <tag></tag>
   <elementGuidId>b8cb3aac-440d-4c8d-b5d6-73bc7f66a6f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='edit_mdb_company_2561385']/div[2]/div/div/div[6]/div/p/a</value>
   </webElementProperties>
</WebElementEntity>
