<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link-edit-AddAddress</name>
   <tag></tag>
   <elementGuidId>82ee41ae-71fe-41fe-bf62-983e183ea196</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='mdb_company_addresses_attributes_0_deliverability']</value>
   </webElementProperties>
</WebElementEntity>
