<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select-edit-AddressType</name>
   <tag></tag>
   <elementGuidId>67ad7ebf-4ea2-462c-89cd-668b089745cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div/div[1]/div[7]/form/div[2]/div/div/div[10]/div/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div/div[1]/div[7]/form/div[2]/div/div/div[10]/div/p/a</value>
   </webElementProperties>
</WebElementEntity>
