<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select-edit-DeleveStatus</name>
   <tag></tag>
   <elementGuidId>ed6e45df-1a40-4348-a2c9-3d8928c41d67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div/div[1]/div[7]/form/div[2]/div/div/div[2]/div/div[3]/select/option[2]</value>
   </webElementProperties>
</WebElementEntity>
