<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select-edit-DeliverabilityStatus</name>
   <tag></tag>
   <elementGuidId>ccbb5ff0-42aa-4d3a-b8e7-7483802351d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='mdb_company_addresses_attributes_0_deliverability']</value>
   </webElementProperties>
</WebElementEntity>
