<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab-communications</name>
   <tag></tag>
   <elementGuidId>53798895-8089-4b48-a3ae-d9b4440ae086</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[3]/div/div[2]/div/div/ul/li[4]/a/strong</value>
   </webElementProperties>
</WebElementEntity>
