<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab-incentives</name>
   <tag></tag>
   <elementGuidId>baa9bac1-be0e-43ad-b3a6-d15e2664d0f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[3]/div/div[2]/div/div/ul/li[4]/a/strong</value>
   </webElementProperties>
</WebElementEntity>
