<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-EditCorn</name>
   <tag></tag>
   <elementGuidId>a004554a-b4be-4389-ba7b-78850dc965f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='Corn']/div/table/tbody/tr[2]/td[4]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='Corn']/div/table/tbody/tr/td[4]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
