<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-AddCorn</name>
   <tag></tag>
   <elementGuidId>d92d495b-bfce-4d09-988d-63d51dce1a27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='new_business_plan_purchase_intention']/div[2]/div[4]/a/i</value>
   </webElementProperties>
</WebElementEntity>
