<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select-UOM</name>
   <tag></tag>
   <elementGuidId>a6523889-1326-48bd-9d1b-23efa2c6ebd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='edit_mdb_company_2561385']/div[2]/div/div/div[3]/div/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;intention_uom_select&quot;]</value>
   </webElementProperties>
</WebElementEntity>
