<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab-Corn</name>
   <tag></tag>
   <elementGuidId>6a116660-4392-47fa-b3c7-3d22bd453ada</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='edit_mdb_company_2561385']/div[2]/div/div/div[3]/div/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='accordion2']/div[1]/div[1]/a/h4</value>
   </webElementProperties>
</WebElementEntity>
