<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab-AgronomicPlan</name>
   <tag></tag>
   <elementGuidId>631edb8c-5d3b-4109-a04c-5e6e3ab03ce4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[3]/div/div[2]/div/div/ul/li[4]/a/strong</value>
   </webElementProperties>
</WebElementEntity>
