<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input-ApplicationAcre</name>
   <tag></tag>
   <elementGuidId>1f84bf40-bd2a-4df9-8ac0-8cd30b9c907d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='new_business_plan_purchase_intention']/div[1]/div/input</value>
   </webElementProperties>
</WebElementEntity>
