<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-DeleteCorn</name>
   <tag></tag>
   <elementGuidId>bd8f7e46-ac25-4357-9108-6afa3b69b59b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='Corn']/div/table/tbody/tr/td[4]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
