<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input-ApplicationAcre</name>
   <tag></tag>
   <elementGuidId>97cec28f-e521-47d3-bc58-12d143c36f5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='new_business_plan_purchase_intention']/div[1]/div/input</value>
   </webElementProperties>
</WebElementEntity>
