<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select-Product</name>
   <tag></tag>
   <elementGuidId>9e824aaa-bcdb-4ad3-b11c-323a6282b098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div/div[2]/div/div/div/div[1]/div/div[4]/div/div[1]/div[2]/div/form/div[2]/div[1]/div/a/span</value>
   </webElementProperties>
</WebElementEntity>
